-- alter table : 테이블 수정
-- add column : 컬럼 추가ALTER
CREATE TABLE MyTable18(
	col1 INT,
    col2 INT
);

ALTER TABLE MyTable18
ADD COLUMN col3 INT;
ALTER TABLE MyTable18
ADD COLUMN col4 INT NOT NULL UNIQUE DEFAULT 0;
ALTER TABLE MyTable18
ADD COLUMN col7 VARCHAR(255) NOT NULL UNIQUE DEFAULT 'EMPTY';
DESC MyTable18;